# Generated by Django 4.2.20 on 2025-03-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadeddata',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Загружены в шину'), (2, 'В обработке'), (3, 'Обработаны'), (4, 'Нет данных'), (5, 'Ошибка при обработке')], default=None, null=True, verbose_name='Статус'),
        ),
    ]
