# Generated by Django 4.2.13 on 2024-06-17 08:46
from django.db import migrations

from config_ui.init_data.settings import ui_settings


def load_data(apps, schema_editor):
    UiSettings = apps.get_model("config_ui", "UiSettings")
    for s in ui_settings:
        try:
            UiSettings(code=s.code, value_type=s.value_type, value=s.value).save()
        except Exception as ex:
            print(f"Не удалось сохранить настройку {s}. {ex}")


def rollback_load_data(apps, schema_editor):
    UiSettings = apps.get_model("config_ui", "UiSettings")
    for s in ui_settings:
        try:
            setting = UiSettings.objects.get(code=s.code, value_type=s.value_type, value=s.value)
        except Exception:
            print(f"Настройки {s} в базе данных не найдено.")
            continue
        else:
            setting.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('config_ui', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, rollback_load_data),
    ]
