# Generated by Django 4.2.13 on 2025-02-07 10:30
from django.db import migrations

from config_ui.init_data.pdata import load as pdata_load


def load_data(apps, schema_editor):
    pdata_load.load_pasp_config()


def rollback_load_data(apps, schema_editor):
    pdata_load.rollback_pasp_config()


class Migration(migrations.Migration):

    dependencies = [
        ('config_ui', '0002_load_settings'),
    ]

    operations = [
        migrations.RunPython(load_data, rollback_load_data),
    ]
