# Generated by Django 4.2.20 on 2025-03-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_ui', '0003_load_settings_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageBlock',
        ),
    ]
