# Generated by Django 4.2.20 on 2025-03-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_ui', '0005_load_asset_status_page_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_ui.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_ui.blocktype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_ui.pagetype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='passportsignals',
            name='pdata_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_ui.passportcategories', verbose_name='Категория паспортных данных'),
        ),
    ]
