# Generated by Django 4.2.20 on 2025-03-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.assetstype', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='assetstypecharttabs',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.assetstype', verbose_name='Категория оборудования'),
        ),
        migrations.AlterField(
            model_name='assetstypecharttabs',
            name='chart_tab',
            field=models.ForeignKey(db_column='chart_tab', on_delete=django.db.models.deletion.PROTECT, to='dashboard.charttabs', verbose_name='Вкладка графиков'),
        ),
        migrations.AlterField(
            model_name='devicemodels',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.devicetypes', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='access_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.accesspoints', verbose_name='Точка доступа'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.devicemodels', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='protocol',
            field=models.ForeignKey(blank=True, db_column='protocol', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.protocols', verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='schedule', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.schedules', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='manualmeasurements',
            name='signal',
            field=models.ForeignKey(db_column='signal_id', on_delete=django.db.models.deletion.PROTECT, to='dashboard.signals', verbose_name='Сигнал'),
        ),
        migrations.AlterField(
            model_name='params',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.assets', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='params',
            name='code',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.PROTECT, to='dashboard.signalsguide', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='asset',
            field=models.ForeignKey(blank=True, db_column='asset', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.assets', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='code',
            field=models.ForeignKey(blank=True, db_column='code', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.signalsguide', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='device',
            field=models.ForeignKey(db_column='device', on_delete=django.db.models.deletion.PROTECT, to='dashboard.devices', verbose_name='Прибор мониторинга'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='formula',
            field=models.ForeignKey(blank=True, db_column='formula', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.formulas', verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='schedule',
            field=models.ForeignKey(blank=True, db_column='schedule', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.schedules', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='unit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.measureunits', verbose_name='Ед. измер. источника'),
        ),
        migrations.AlterField(
            model_name='signals',
            name='value_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.modbustypes', verbose_name='Тип данных modbus'),
        ),
        migrations.AlterField(
            model_name='signalscharttabs',
            name='chart_tab',
            field=models.ForeignKey(db_column='chart_tab', on_delete=django.db.models.deletion.PROTECT, to='dashboard.assetstypecharttabs', verbose_name='Вкладка графиков'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.signalсategories', verbose_name='Категория сигнала'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.datatypes', verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='databus_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.databussources', verbose_name='Очередь шины данных'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='dynamic_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.dynamicstorages', verbose_name='Таблица хранения значений'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.signalgroups', verbose_name='Группа сигнала'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='plot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.plottypes', verbose_name='Тип графика'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='sg_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.signaltypes', verbose_name='Тип сигнала'),
        ),
        migrations.AlterField(
            model_name='signalsguide',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.measureunits', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='substations',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'node'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.substations', verbose_name='Входит в'),
        ),
    ]
