# Generated by Django 4.2.20 on 2025-03-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILabels',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Метка API',
                'verbose_name_plural': 'API. Метки',
                'db_table': 'api_labels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiagMsgTemplates',
            fields=[
                ('num_code', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('code', models.CharField(max_length=200, verbose_name='Строковый код')),
            ],
            options={
                'verbose_name': 'Код шаблона диагностического сообщения',
                'verbose_name_plural': 'Шаблоны диагностических сообщений. Коды',
                'db_table': 'diagmsg_templates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Interfacelabels',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Метка пользовательского интерфейса',
                'verbose_name_plural': 'Пользовательский интерфейс. Метки',
                'db_table': 'interface_labels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Langs',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Язык интерфейса',
                'verbose_name_plural': 'Языки интерфейса',
                'db_table': 'langs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SignalsGuideTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
                ('sgn_guide', models.ForeignKey(db_column='sgn_guide', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.signalsguide', verbose_name='Код сигнала')),
            ],
            options={
                'verbose_name': 'Перевод названия кода сигнала',
                'verbose_name_plural': 'Сигналы. Коды. Переводы',
                'db_table': 'signals_guide_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SignalsCategoriesTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.signalсategories', verbose_name='Категория сигнала')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Перевод названия категории сигнала',
                'verbose_name_plural': 'Сигналы. Категории. Переводы',
                'db_table': 'signals_categories_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PassportCategoriesTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='Код категории')),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Перевод категории паспортных данных',
                'verbose_name_plural': 'Паспорт. Категории данных. Переводы',
                'db_table': 'passport_categories_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeasureUnitsTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
                ('unit', models.ForeignKey(db_column='unit', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.measureunits', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Перевод названия единицы измерения',
                'verbose_name_plural': 'Сигналы. Единицы измерения. Переводы',
                'db_table': 'measure_units_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InterfaceTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('label', models.ForeignKey(db_column='label', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.interfacelabels', verbose_name='Метка польз. интерфейса')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Перевод метки пользовательского интерфейса',
                'verbose_name_plural': 'Пользовательский интерфейс. Переводы меток',
                'db_table': 'interface_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiagMsgTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1500, verbose_name='Содержание')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
                ('msg', models.ForeignKey(db_column='msg_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.diagmsgtemplates', verbose_name='Шаблон диаг. сообщения')),
            ],
            options={
                'verbose_name': 'Перевод шаблона диагностического сообщения',
                'verbose_name_plural': 'Шаблоны диагностических сообщений. Переводы',
                'db_table': 'diagmsg_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiagMsgLevelTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
                ('level', models.ForeignKey(db_column='level', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.diagmsglevel', verbose_name='Уровень критичности')),
            ],
            options={
                'verbose_name': 'Перевод уровня критичности диаг. сообщений',
                'verbose_name_plural': 'Уровни критичности диаг. сообщений. Переводы',
                'db_table': 'diag_msg_level_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetsTypeTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('a_type', models.ForeignKey(db_column='a_type', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.assetstype', verbose_name='Категория оборудования')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Перевод категории оборудования',
                'verbose_name_plural': 'Категории оборудования. Переводы',
                'db_table': 'asset_type_translts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='APILabelsTranslts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Содержание')),
                ('label', models.ForeignKey(db_column='label', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.apilabels', verbose_name='Метка API')),
                ('lang', models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.DO_NOTHING, to='localization.langs', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Перевод метки API',
                'verbose_name_plural': 'API. Метки. Переводы меток',
                'db_table': 'api_labels_translts',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='signalsguidetranslts',
            constraint=models.UniqueConstraint(fields=('sgn_guide', 'lang'), name='unique_signalsguidetranslts'),
        ),
        migrations.AddConstraint(
            model_name='signalscategoriestranslts',
            constraint=models.UniqueConstraint(fields=('category', 'lang'), name='unique_signalscategoriestranslts'),
        ),
        migrations.AddConstraint(
            model_name='passportcategoriestranslts',
            constraint=models.UniqueConstraint(fields=('code', 'lang'), name='unique_passportcategoriestranslts'),
        ),
        migrations.AddConstraint(
            model_name='measureunitstranslts',
            constraint=models.UniqueConstraint(fields=('unit', 'lang'), name='unique_measureunitstranslts'),
        ),
        migrations.AddConstraint(
            model_name='interfacetranslts',
            constraint=models.UniqueConstraint(fields=('label', 'lang'), name='unique_interfacetranslts'),
        ),
        migrations.AddConstraint(
            model_name='diagmsgtranslts',
            constraint=models.UniqueConstraint(fields=('msg', 'lang'), name='unique_diagmsgtranslts'),
        ),
        migrations.AddConstraint(
            model_name='diagmsgleveltranslts',
            constraint=models.UniqueConstraint(fields=('level', 'lang'), name='unique_diagmsgleveltranslts'),
        ),
        migrations.AddConstraint(
            model_name='assetstypetranslts',
            constraint=models.UniqueConstraint(fields=('a_type', 'lang'), name='unique_assetstypetranslts'),
        ),
        migrations.AddConstraint(
            model_name='apilabelstranslts',
            constraint=models.UniqueConstraint(fields=('label', 'lang'), name='unique_apilabelstranslts'),
        ),
    ]
