# Generated by Django 4.2.13 on 2024-06-17 08:46
from django.db import migrations

from main.settings import BASE_DIR
from localization.services.importing.use_cases import import_in_migration
from localization.services.importing.import_schemes import imports_for_migration


def load_data(apps, schema_editor):
    import_in_migration(
        BASE_DIR.joinpath("localization", "init_data", "localization_data.xlsx"),
        imports_for_migration)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
