# Generated by Django 4.2.13 on 2024-06-17 08:46
from django.db import migrations

from main.settings import BASE_DIR
from localization.services.importing.use_cases import import_in_migration
from localization.services.importing.import_schemes import imports_pdata_categories_for_migration


def load_data(apps, schema_editor):
    import_in_migration(
        BASE_DIR.joinpath("localization", "init_data", "localization_data.xlsx"),
        imports_pdata_categories_for_migration)


def rollback_load_data(apps, schema_editor):
    pdata_categories_translts = apps.get_model("localization", "PassportCategoriesTranslts")
    try:
        pdata_categories_translts.objects.all().delete()
    except Exception as ex:
        print(
            f"Не удалось очистить таблицу {pdata_categories_translts.Meta.db_table}."
            f" {ex}")


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_load_localization'),
    ]

    operations = [
        migrations.RunPython(load_data, rollback_load_data),
    ]
