# Generated by Django 4.2.20 on 2025-03-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_assets_type_and_more'),
        ('localization', '0003_load_localization_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilabelstranslts',
            name='label',
            field=models.ForeignKey(db_column='label', on_delete=django.db.models.deletion.PROTECT, to='localization.apilabels', verbose_name='Метка API'),
        ),
        migrations.AlterField(
            model_name='apilabelstranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='assetstypetranslts',
            name='a_type',
            field=models.ForeignKey(db_column='a_type', on_delete=django.db.models.deletion.PROTECT, to='dashboard.assetstype', verbose_name='Категория оборудования'),
        ),
        migrations.AlterField(
            model_name='assetstypetranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='diagmsgleveltranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='diagmsgleveltranslts',
            name='level',
            field=models.ForeignKey(db_column='level', on_delete=django.db.models.deletion.PROTECT, to='dashboard.diagmsglevel', verbose_name='Уровень критичности'),
        ),
        migrations.AlterField(
            model_name='diagmsgtranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='diagmsgtranslts',
            name='msg',
            field=models.ForeignKey(db_column='msg_id', on_delete=django.db.models.deletion.PROTECT, to='localization.diagmsgtemplates', verbose_name='Шаблон диаг. сообщения'),
        ),
        migrations.AlterField(
            model_name='interfacetranslts',
            name='label',
            field=models.ForeignKey(db_column='label', on_delete=django.db.models.deletion.PROTECT, to='localization.interfacelabels', verbose_name='Метка польз. интерфейса'),
        ),
        migrations.AlterField(
            model_name='interfacetranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='measureunitstranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='measureunitstranslts',
            name='unit',
            field=models.ForeignKey(db_column='unit', on_delete=django.db.models.deletion.PROTECT, to='dashboard.measureunits', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='passportcategoriestranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='signalscategoriestranslts',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, to='dashboard.signalсategories', verbose_name='Категория сигнала'),
        ),
        migrations.AlterField(
            model_name='signalscategoriestranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='signalsguidetranslts',
            name='lang',
            field=models.ForeignKey(db_column='lang_id', on_delete=django.db.models.deletion.PROTECT, to='localization.langs', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='signalsguidetranslts',
            name='sgn_guide',
            field=models.ForeignKey(db_column='sgn_guide', on_delete=django.db.models.deletion.PROTECT, to='dashboard.signalsguide', verbose_name='Код сигнала'),
        ),
    ]
